### ISSUE TITLE
Crashing on ePub load 

### ISSUE THREAD

**Issue by zekera** [hyphen-reader/hyphen#14]
![image](https://cloud.githubusercontent.com/assets/16052704/11448802/a9cde2be-9515-11e5-927a-645fd397dbb6.png)
Having issues with file loading and crashing on both a failed load and on "send help email".

Sorry if i didn't add the bug label correctly...don't see where to add labels.

**Comment by matt-curtis** [comment]
Could you [upload](http://datafilehost.com) the ePub that's causing this?

**Comment by zekera** [comment]
http://www.datafilehost.com/d/bbb493ce

Uploaded, maybe also of note is it happens with all of these books, not just this book.

Thanks!

**Comment by matt-curtis** [comment]
Thanks! I'm looking into this.

**Comment by zekera** [comment]
Great, thanks

**Comment by matt-curtis** [comment]
Quick update: I've fixed this in the next version. Thanks for bringing it to my attention.

**Comment by zekera** [comment]
Sounds good - when is next code deployment?  Thanks!

**Comment by matt-curtis** [comment]
There are still other things to fix before this release is ready, so I can't say yet.

**Comment by zekera** [comment]
Hi,

Not resolved - different behavior (no app crash) but still cannot load the
books.  Do I need to file a new bug?

Also, there's books that I cannot import from the same series. Should that
be its own bug?
I can send a case tomorrow.

Thx

**Comment by matt-curtis** [comment]
Could you [upload](http://sendspace.com/) all of the ePubs you are having difficulty with? I tested the ePub you uploaded here, without an issue. Do note that ePubs you were having issues with before the latest 1.1.1 version will need to be deleted and re-imported.
